services:
  - type: web
    name: jarvis-md
    env: docker
    branch: main
    repo: https://github.com/Loki-Xer/jarvis-md.git
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_IDJarvis_b0ae_cc71_5c1b_5494_7ab5_ee60_f5e5_e614
        sync: false
      - key: DATABASE_URL
        sync: false
